### ISSUE TITLE
Panic while running units

### ISSUE THREAD

**Issue by erikh** [contiv/netplugin#355]
```
INFO[0036] Switch 00:00:08:00:27:3f:ff:c3 connected
INFO[0036] Switch connected(svcProxy).
INFO[0036] Switch connected(policyAgent).
INFO[0036] Installing initial flow entries
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x10 pc=0x65a9ea]

goroutine 757 [running]:
panic(0xe28c60, 0xc82000e170)
        /usr/local/go/src/runtime/panic.go:481 +0x3e6
github.com/contiv/ofnet/ofctrl.(*Table).NewFlow(0x0, 0x1, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /opt/golang/src/github.com/contiv/netplugin/Godeps/_workspace/src/github.com/contiv/ofnet/ofctrl/fgraphTable.go:61 +0x28a
github.com/contiv/ofnet.(*ServiceProxy).InitSNATTable(0xc82012ed70, 0xc820331407, 0x0, 0x0)
        /opt/golang/src/github.com/contiv/netplugin/Godeps/_workspace/src/github.com/contiv/ofnet/ofnetSvcProxy.go:648 +0x30f
github.com/contiv/ofnet.(*VlanBridge).initFgraph(0xc82012ed20, 0x0, 0x0)
        /opt/golang/src/github.com/contiv/netplugin/Godeps/_workspace/src/github.com/contiv/ofnet/vlanBridge.go:321 +0x30b
github.com/contiv/ofnet.(*VlanBridge).SwitchConnected(0xc82012ed20, 0xc8201c6f60)
        /opt/golang/src/github.com/contiv/netplugin/Godeps/_workspace/src/github.com/contiv/ofnet/vlanBridge.go:83 +0x7e
github.com/contiv/ofnet.(*OfnetAgent).SwitchConnected(0xc820317c20, 0xc8201c6f60)
        /opt/golang/src/github.com/contiv/netplugin/Godeps/_workspace/src/github.com/contiv/ofnet/ofnetAgent.go:246 +0x189
github.com/contiv/ofnet/ofctrl.(*OFSwitch).switchConnected(0xc8201c6f60)
        /opt/golang/src/github.com/contiv/netplugin/Godeps/_workspace/src/github.com/contiv/ofnet/ofctrl/ofSwitch.go:100 +0x52
github.com/contiv/ofnet/ofctrl.NewSwitch(0xc820390280, 0xc820402210, 0x8, 0x8, 0x7f5592e70dc0, 0xc8202fbc20, 0x0)
        /opt/golang/src/github.com/contiv/netplugin/Godeps/_workspace/src/github.com/contiv/ofnet/ofctrl/ofSwitch.go:73 +0x357
github.com/contiv/ofnet/ofctrl.(*Controller).handleConnection(0xc8206cc860, 0x7f5592e271a0, 0xc82048b4a0)
        /opt/golang/src/github.com/contiv/netplugin/Godeps/_workspace/src/github.com/contiv/ofnet/ofctrl/ofctrl.go:145 +0xa04
created by github.com/contiv/ofnet/ofctrl.(*Controller).Listen
        /opt/golang/src/github.com/contiv/netplugin/Godeps/_workspace/src/github.com/contiv/ofnet/ofctrl/ofctrl.go:91 +0x4c5
exit status 2
FAIL    github.com/contiv/netplugin/drivers     36.273s
```

This happened while running the units on my ansible fork; please reach out to me if you cannot find or reproduce the error, I can give you the branch with the VMs/ansible to create the environment.

I have not seen this before in several test runs, so I am not certain what is causing the error.

**Comment by jojimt** [comment]
I tried with the top of the tree and see no issue. May be you're missing a godep update or something?

**Comment by erikh** [comment]
Nope, still using the same kit from master.

https://github.com/contiv/ofnet/blob/master/ofctrl/fgraphTable.go#L49-L64

flowDB is nil in this case. Now, I have no idea how it gets TO BE nil but it is here.

It looks like it's not getting initialized properly.

**Comment by erikh** [comment]
OH FWIW: I have not been able to reproduce this for a while. The only thing I did during that time that was truly odd was detach the network from the machine.

**Comment by erikh** [comment]
(physically)

**Comment by erikh** [comment]
it was not detached when I ran the tests. oof, sorry about all this spam.

**Comment by gaurav-dalvi** [comment]
@jojimt @erikh can we close this issue now ?

**Comment by erikh** [comment]
feel free to if you can't reproduce

**Comment by jojimt** [comment]
Closing as we don't seem to be able to repro this.
