### ISSUE TITLE
netplugin crashing after netctl bgp command

### ISSUE THREAD

**Issue by gaurav-dalvi** [contiv/netplugin#503]
Steps to reproduce : 
1: run net_demo_installer (any version is fine)
2: run similar command like this 
`netctl bgp create contiv-demo-swarm-l3-1 -router-ip="50.1.1.1/24" --as="65002" --neighbor-as="500" --neighbor="50.1.1.2"`

3: check netplugin status.

```
Aug 08 18:12:58 contiv-demo-swarm-l3-1 netplugin[13597]: time="Aug  8 18:12:58.022911130" level=info msg="AddMaster for {HostAddr:10.193.246.22 Port:9001}"
Aug 08 18:12:58 contiv-demo-swarm-l3-1 netplugin[13597]: time="Aug  8 18:12:58.022923256" level=info msg="Adding master: {HostAddr:10.193.246.22 HostPort:9001}"
Aug 08 18:12:58 contiv-demo-swarm-l3-1 netplugin[13597]: time="Aug  8 18:12:58.023235228" level=info msg="Adding master: {HostAddr:10.193.246.22 HostPort:9001}"
Aug 08 18:13:26 contiv-demo-swarm-l3-1 netplugin[13597]: time="Aug  8 18:13:26.215121714" level=info msg="Received \"create\" for Bgp: \"contiv-demo-swarm-l3-1\""
Aug 08 18:13:26 contiv-demo-swarm-l3-1 netplugin[13597]: time="Aug  8 18:13:26.215248613" level=info msg="Reading from etcd State %scontiv-demo-swarm-l3-1"
Aug 08 18:13:26 contiv-demo-swarm-l3-1 netplugin[13597]: time="Aug  8 18:13:26.223396758" level=info msg="create Bgp Server contiv-demo-swarm-l3-1 \n"
Aug 08 18:13:26 contiv-demo-swarm-l3-1 netplugin[13597]: time="Aug  8 18:13:26.223476884" level=info msg="Received request add bgp config: RouterIp:50.1.1.1/24,As:65002,NeighborAs:500,PeerIP:50.1.1.2"
Aug 08 18:13:26 contiv-demo-swarm-l3-1 netplugin[13597]: panic: runtime error: invalid memory address or nil pointer dereference
Aug 08 18:13:26 contiv-demo-swarm-l3-1 netplugin[13597]: [signal 0xb code=0x1 addr=0x40 pc=0x712f11]
Aug 08 18:13:26 contiv-demo-swarm-l3-1 netplugin[13597]: goroutine 212 [running]:
Aug 08 18:13:26 contiv-demo-swarm-l3-1 netplugin[13597]: github.com/contiv/ofnet.(*OfnetAgent).AddBgp(0xc820511c20, 0xc82022f8b0, 0xb, 0xc82022f8c0, 0x5, 0xc82022f8d0, 0x3, 0xc82022f8e0, 0x8, 0x0, ...)
Aug 08 18:13:26 contiv-demo-swarm-l3-1 netplugin[13597]: /opt/gopath/src/github.com/contiv/netplugin/Godeps/_workspace/src/github.com/contiv/ofnet/ofnetAgent.go:735 +0x411
Aug 08 18:13:26 contiv-demo-swarm-l3-1 netplugin[13597]: github.com/contiv/netplugin/drivers.(*OvsSwitch).AddBgp(0xc8203db830, 0xc8205c9540, 0x16, 0xc82022f8b0, 0xb, 0xc82022f8c0, 0x5, 0xc82022f8d0, 0x3, 0xc82022f8e0, ...)
Aug 08 18:13:26 contiv-demo-swarm-l3-1 netplugin[13597]: /opt/gopath/src/github.com/contiv/netplugin/drivers/ovsSwitch.go:596 +0x114
Aug 08 18:13:26 contiv-demo-swarm-l3-1 netplugin[13597]: github.com/contiv/netplugin/drivers.(*OvsDriver).AddBgp(0xc8201434c0, 0xc82022dce0, 0x16, 0x0, 0x0)
Aug 08 18:13:26 contiv-demo-swarm-l3-1 netplugin[13597]: /opt/gopath/src/github.com/contiv/netplugin/drivers/ovsdriver.go:472 +0x510
Aug 08 18:13:26 contiv-demo-swarm-l3-1 netplugin[13597]: github.com/contiv/netplugin/netplugin/plugin.(*NetPlugin).AddBgp(0xc820373c40, 0xc82022dce0, 0x16, 0x0, 0x0)
Aug 08 18:13:26 contiv-demo-swarm-l3-1 netplugin[13597]: /opt/gopath/src/github.com/contiv/netplugin/netplugin/plugin/netplugin.go:181 +0x5a
Aug 08 18:13:26 contiv-demo-swarm-l3-1 netplugin[13597]: main.processBgpEvent(0xc820373c40, 0xc820374f20, 0x16, 0x7ffd5c5b6eec, 0x6, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
Aug 08 18:13:26 contiv-demo-swarm-l3-1 netplugin[13597]: /opt/gopath/src/github.com/contiv/netplugin/netplugin/netd.go:295 +0x431
Aug 08 18:13:26 contiv-demo-swarm-l3-1 netplugin[13597]: main.processStateEvent(0xc820373c40, 0xc820374f20, 0x16, 0x7ffd5c5b6eec, 0x6, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
Aug 08 18:13:26 contiv-demo-swarm-l3-1 netplugin[13597]: /opt/gopath/src/github.com/contiv/netplugin/netplugin/netd.go:359 +0x5ef
```

**Comment by abhinandanpb** [comment]
@gaurav-dalvi like i said earlier i am in the final stages of fixing this issue. The issue is in ofnet and not netplugin. https://github.com/contiv/ofnet/issues/53.
Can you post the netctl global inspect ? And see if the cluster is in routing mode ?

**Comment by gaurav-dalvi** [comment]
netctl global inspect
INFO[0000] Inspecting global                            
{
  "Config": {
    "key": "global",
    "name": "global",
    "networkInfraType": "default",
    "vlans": "1-4094",
    "vxlans": "1-10000"
  },
  "Oper": {}
}

**Comment by gaurav-dalvi** [comment]
Yes @abhinandanpb . I am just opening issue for tracking purpose in future. I will close it as soon as it passes.

**Comment by gaurav-dalvi** [comment]
Not seeing the issue with this version `v0.1-08-17-2016.09-11-39.UTC`
Closing it !
