### ISSUE TITLE
Not able to run ACI system tests with current code (08/19)

### ISSUE THREAD

**Issue by gaurav-dalvi** [contiv/netplugin#533]
Error log:

```
INFO[0000] Pulling contiv/alpine on all nodes           
INFO[0001] Copying netmaster binary to /home/admin/bin  
INFO[0001] Copying /home/admin/bin/netmaster binary to IP= 10.193.246.5 and Directory = /home/admin/bin/netmaster 
INFO[0002] Copying netplugin binary to /home/admin/bin  
INFO[0002] Copying /home/admin/bin/netplugin binary to IP= 10.193.246.5 and Directory = /home/admin/bin/netplugin 
INFO[0002] Copying netctl binary to /home/admin/bin     
INFO[0002] Copying /home/admin/bin/netctl binary to IP= 10.193.246.5 and Directory = /home/admin/bin/netctl 
INFO[0003] Copying contivk8s binary to /home/admin/bin  
INFO[0003] Copying /home/admin/bin/contivk8s binary to IP= 10.193.246.5 and Directory = /home/admin/bin/contivk8s 
INFO[0003] ============================= systemtestSuite.TestACIPingGateway starting ========================== 
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0xe8 pc=0x501315]

goroutine 134 [running]:
panic(0x930be0, 0xc8200100d0)
	/usr/local/go/src/runtime/panic.go:464 +0x3e6
github.com/contiv/netplugin/test/systemtests.(*systemtestSuite).runContainersOnNode.func1(0x9d6530, 0x6, 0x9e2770, 0x9, 0x9d6fd8, 0x4, 0xc820148c30, 0xc82000b0e0, 0xc820122bd8, 0xc820118860, ...)
	/home/admin/src/github.com/contiv/netplugin/test/systemtests/util_test.go:278 +0x375
created by github.com/contiv/netplugin/test/systemtests.(*systemtestSuite).runContainersOnNode
	/home/admin/src/github.com/contiv/netplugin/test/systemtests/util_test.go:288 +0x1be
exit status 2
FAIL	github.com/contiv/netplugin/test/systemtests	5.824s

```

**Comment by gaurav-dalvi** [comment]
This is fixed because of this PR : https://github.com/contiv/netplugin/pull/555.
Closing it !
