### ISSUE TITLE
netct group inspect throws go panic error

### ISSUE THREAD

**Issue by gaurav-dalvi** [contiv/netplugin#735]
```
netctl group inspect
panic: runtime error: index out of range

goroutine 1 [running]:
panic(0x6ff9a0, 0xc420012110)
	/usr/local/go/src/runtime/panic.go:500 +0x1a1
github.com/contiv/netplugin/netctl.inspectEndpointGroup(0xc420095320)
	/opt/gopath/src/github.com/contiv/netplugin/netctl/netctl.go:662 +0x2c1
github.com/contiv/netplugin/vendor/github.com/codegangsta/cli.Command.Run(0x753214, 0x7, 0x0, 0x0, 0x0, 0x0, 0x0, 0x7590b8, 0x17, 0x0, ...)
	/opt/gopath/src/github.com/contiv/netplugin/vendor/github.com/codegangsta/cli/command.go:131 +0x79d
github.com/contiv/netplugin/vendor/github.com/codegangsta/cli.(*App).RunAsSubcommand(0xc4200950e0, 0xc420094fc0, 0x0, 0x0)
	/opt/gopath/src/github.com/contiv/netplugin/vendor/github.com/codegangsta/cli/app.go:280 +0x87b
github.com/contiv/netplugin/vendor/github.com/codegangsta/cli.Command.startApp(0x752970, 0x5, 0x0, 0x0, 0x0, 0x0, 0x0, 0x75d76e, 0x21, 0x0, ...)
	/opt/gopath/src/github.com/contiv/netplugin/vendor/github.com/codegangsta/cli/command.go:209 +0x6e6
github.com/contiv/netplugin/vendor/github.com/codegangsta/cli.Command.Run(0x752970, 0x5, 0x0, 0x0, 0x0, 0x0, 0x0, 0x75d76e, 0x21, 0x0, ...)
	/opt/gopath/src/github.com/contiv/netplugin/vendor/github.com/codegangsta/cli/command.go:59 +0x11d9
github.com/contiv/netplugin/vendor/github.com/codegangsta/cli.(*App).Run(0xc420094ea0, 0xc4200740c0, 0x3, 0x3, 0x0, 0x0)
	/opt/gopath/src/github.com/contiv/netplugin/vendor/github.com/codegangsta/cli/app.go:173 +0xa35
main.main()
	/opt/gopath/src/github.com/contiv/netplugin/netctl/netctl/main.go:16 +0x11d
[vagrant@netplugin-node1 netplugin]$ netctl group inspect -t t1
panic: runtime error: index out of range

goroutine 1 [running]:
panic(0x6ff9a0, 0xc420012110)
	/usr/local/go/src/runtime/panic.go:500 +0x1a1
github.com/contiv/netplugin/netctl.inspectEndpointGroup(0xc420095440)
	/opt/gopath/src/github.com/contiv/netplugin/netctl/netctl.go:662 +0x2c1
github.com/contiv/netplugin/vendor/github.com/codegangsta/cli.Command.Run(0x753214, 0x7, 0x0, 0x0, 0x0, 0x0, 0x0, 0x7590b8, 0x17, 0x0, ...)
	/opt/gopath/src/github.com/contiv/netplugin/vendor/github.com/codegangsta/cli/command.go:131 +0x79d
github.com/contiv/netplugin/vendor/github.com/codegangsta/cli.(*App).RunAsSubcommand(0xc420095200, 0xc4200950e0, 0x0, 0x0)
	/opt/gopath/src/github.com/contiv/netplugin/vendor/github.com/codegangsta/cli/app.go:280 +0x87b
github.com/contiv/netplugin/vendor/github.com/codegangsta/cli.Command.startApp(0x752970, 0x5, 0x0, 0x0, 0x0, 0x0, 0x0, 0x75d76e, 0x21, 0x0, ...)
	/opt/gopath/src/github.com/contiv/netplugin/vendor/github.com/codegangsta/cli/command.go:209 +0x6e6
github.com/contiv/netplugin/vendor/github.com/codegangsta/cli.Command.Run(0x752970, 0x5, 0x0, 0x0, 0x0, 0x0, 0x0, 0x75d76e, 0x21, 0x0, ...)
	/opt/gopath/src/github.com/contiv/netplugin/vendor/github.com/codegangsta/cli/command.go:59 +0x11d9
github.com/contiv/netplugin/vendor/github.com/codegangsta/cli.(*App).Run(0xc420094fc0, 0xc420082000, 0x5, 0x5, 0x0, 0x0)
	/opt/gopath/src/github.com/contiv/netplugin/vendor/github.com/codegangsta/cli/app.go:173 +0xa35
main.main()
	/opt/gopath/src/github.com/contiv/netplugin/netctl/netctl/main.go:16 +0x11d
```

Error is not happening for netctl net inspect .

```
netctl net inspect -t t1
ERRO[0000] Network name required
NAME:
   netctl network inspect - Inspect a Network

USAGE:
   netctl network inspect [command options] [network]

OPTIONS:
   --tenant, -t "default"	Name of the tenant
   --json, -j			Output list in JSON format

```

**Comment by gaurav-dalvi** [comment]
In the PR

**Comment by dseevr** [comment]
Closed by https://github.com/contiv/netplugin/pull/736
