### ISSUE TITLE
make demo gets stuck if I use consul

### ISSUE THREAD

**Issue by gaurav-dalvi** [contiv/netplugin#822]
Steps to repro : 
1: git clone ----
2: cd netplugin
3: export CONTIV_CLUSTER_STORE: “consul://localhost:8500

error

```
run: curl -X DELETE localhost:8500/v1/kv/docker?recurse=true
stdout(0):true
stderr:   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100     4  100     4    0     0    259      0 --:--:-- --:--:-- --:--:--   266

run: docker ps -a | grep alpine | awk '{print $1}' | xargs -r docker rm -fv
run: sudo ovs-vsctl del-br contivVxlanBridge
stdout(1):
stderr: ovs-vsctl: no bridge named contivVxlanBridge

run: sudo ovs-vsctl del-br contivVlanBridge
stdout(1):
stderr: ovs-vsctl: no bridge named contivVlanBridge

run: ifconfig | grep -e vport | awk '{print $1}' | xargs -r -n1 -I{} sudo ip link delete {} type veth
stderr: bash: ifconfig: command not found

run: sudo rm -f /var/run/docker/plugins/netplugin.sock
run: sudo rm -f /tmp/net*
Starting netplugin on netplugin-node1
Connecting to 192.168.2.10 with userid: vagrant password: vagrant
run: sudo /opt/gopath/bin/netplugin -plugin-mode docker -vlan-if eth2 -vlan-if eth3 -cluster-store consul://localhost:8500 > /tmp/netplugin.log 2>&1
 Starting netplugin on netplugin-node2
Connecting to 192.168.2.11 with userid: vagrant password: vagrant
run: sudo /opt/gopath/bin/netplugin -plugin-mode docker -vlan-if eth2 -vlan-if eth3 -cluster-store consul://localhost:8500 > /tmp/netplugin.log 2>&1
 Starting netplugin on netplugin-node3
Connecting to 192.168.2.12 with userid: vagrant password: vagrant
run: sudo /opt/gopath/bin/netplugin -plugin-mode docker -vlan-if eth2 -vlan-if eth3 -cluster-store consul://localhost:8500 > /tmp/netplugin.log 2>&1
Starting netmaster on netplugin-node1
Connecting to 192.168.2.10 with userid: vagrant password: vagrant
Traceback (most recent call last):
  File "./startPlugin.py", line 25, in <module>
    testbed = api.tbed.Testbed(addrList, args.user, args.password, args.binpath, args.plugintype)
  File "/opt/gopath/src/github.com/contiv/netplugin/scripts/python/api/tbed.py", line 38, in __init__
    self.startPluginBinaries()
  File "/opt/gopath/src/github.com/contiv/netplugin/scripts/python/api/tbed.py", line 55, in startPluginBinaries
    node.startNetmaster()
  File "/opt/gopath/src/github.com/contiv/netplugin/scripts/python/api/tnode.py", line 106, in startNetmaster
    listenPort = os.environ["CONTIV_NETMASTER_LISTEN_PORT"]
  File "/usr/lib64/python2.7/UserDict.py", line 23, in __getitem__
    raise KeyError(key)
KeyError: 'CONTIV_NETMASTER_LISTEN_PORT'



```

**Comment by DivyaVavili** [comment]
Fixed by PR #831
