### ISSUE TITLE
Netplugin CRASH when first request to load balancer.

### ISSUE THREAD

**Issue by haoyixin** [contiv/netplugin#891]
first, i've added a lb to contiv, and i got this log from netplugin:

```
time="Jun  6 10:43:07.906824742" level=info msg="[tenant: default]add service name:test-lb, ipadddr: 192.168.111.111" module=nameserver
time="Jun  6 10:43:07.907074202" level=info msg="Received "create" for Service test-lb on tenant default"
time="Jun  6 10:43:07.907132264" level=info msg="Recevied Process Service load balancer event {&{{0xc4200e01a0 test-lb:default} test-lb default default-net [8881:9002:TCP] map[zzz:xxx] 192.168.111.111 map[]}}"
time="Jun  6 10:43:07.907143358" level=info msg="AddSvcSpec: test-lb:default"
time="Jun  6 10:43:07.907164481" level=info msg="sw AddSvcSpec: test-lb:default"
time="Jun  6 10:43:07.907171096" level=info msg="OvsSwitch AddSvcSpec test-lb:default"
time="Jun  6 10:43:07.907247615" level=info msg="AddSvcSpec test-lb:default &{192.168.111.111 [{TCP 8881 9002}]}"
time="Jun  6 10:43:07.907262443" level=info msg="sw AddSvcSpec: test-lb:default"
time="Jun  6 10:43:07.907268457" level=info msg="OvsSwitch AddSvcSpec test-lb:default"
time="Jun  6 10:43:07.907278506" level=info msg="AddSvcSpec test-lb:default &{192.168.111.111 [{TCP 8881 9002}]}"
time="Jun  6 10:43:07.907290119" level=info msg="Node proxy AddSvcSpec: test-lb:default"
time="Jun  6 10:43:07.907298802" level=info msg="add k8s service test-lb:default ip 192.168.111.111" module=nameserver
time="Jun  6 10:43:07.907310490" level=info msg="Service Load Balancer create succeeded"
time="Jun  6 10:43:07.907543478" level=info msg="Received "create" for Service test-lb on tenant default"
time="Jun  6 10:43:07.907574741" level=info msg="Recevied Process Service load balancer event {&{{0xc4200e01a0 test-lb:default} test-lb default default-net [8881:9002:TCP] map[zzz:xxx] 192.168.111.111 map[192.168.111.2:default:0xc42030e580]}}"
time="Jun  6 10:43:07.907583736" level=info msg="AddSvcSpec: test-lb:default"
time="Jun  6 10:43:07.907590661" level=info msg="sw AddSvcSpec: test-lb:default"
time="Jun  6 10:43:07.907596450" level=info msg="OvsSwitch AddSvcSpec test-lb:default"
time="Jun  6 10:43:07.907607044" level=info msg="AddSvcSpec test-lb:default &{192.168.111.111 [{TCP 8881 9002}]}"
time="Jun  6 10:43:07.907603674" level=info msg="[tenant: default]add service name:test-lb, ipadddr: 192.168.111.111" module=nameserver
time="Jun  6 10:43:07.907614720" level=info msg="sw AddSvcSpec: test-lb:default"
time="Jun  6 10:43:07.907620350" level=info msg="OvsSwitch AddSvcSpec test-lb:default"
time="Jun  6 10:43:07.907641928" level=info msg="AddSvcSpec test-lb:default &{192.168.111.111 [{TCP 8881 9002}]}"
time="Jun  6 10:43:07.907654715" level=info msg="Node proxy AddSvcSpec: test-lb:default"
time="Jun  6 10:43:07.907661048" level=info msg="add k8s service test-lb:default ip 192.168.111.111" module=nameserver
time="Jun  6 10:43:07.907670915" level=info msg="Service Load Balancer create succeeded"
time="Jun  6 10:43:07.908300107" level=info msg="Received "create" for Service test-lb:default on tenant [192.168.111.2]"
time="Jun  6 10:43:07.908322445" level=info msg="ProviderUpdate test-lb:default [192.168.111.2]"
time="Jun  6 10:43:07.908420364" level=info msg="ProviderUpdate test-lb:default [192.168.111.2]"
time="Jun  6 10:43:07.908456045" level=info msg="Node proxy AddSvcSpec: test-lb:default [192.168.111.2]"
```

i found nothing abnormal, then:

```
# curl 192.168.111.2:9002

<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 3.2 Final//EN"><html>
<title>Directory listing for /</title>
<body>
<h2>Directory listing for /</h2>
<hr>
<ul>
<li><a href="stderr">stderr</a>
<li><a href="stdout">stdout</a>
</ul>
<hr>
</body>
</html>
```

real server was working, then:

```
# curl 192.168.111.111:8881
```

but it was hanging, and i got this log from netplugin, then netplugin exited:

```
2017/06/06 10:47:32 Unhandled Field: 105 in Class: 1
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x869f56]

goroutine 59 [running]:
panic(0x172f000, 0xc420010040)
	/usr/local/go/src/runtime/panic.go:500 +0x1a1
github.com/haoyixin/netplugin/vendor/github.com/shaleman/libOpenflow/openflow13.(*MatchField).UnmarshalBinary(0xc42077dd30, 0xc4203a3824, 0x68, 0x7dc, 0x1, 0xc4200ce7e0)
	/root/go/src/github.com/haoyixin/netplugin/vendor/github.com/shaleman/libOpenflow/openflow13/match.go:160 +0x136
github.com/haoyixin/netplugin/vendor/github.com/shaleman/libOpenflow/openflow13.(*Match).UnmarshalBinary(0xc4201dadd8, 0xc4203a3818, 0x74, 0x7e8, 0xa0, 0x18aad80)
	/root/go/src/github.com/haoyixin/netplugin/vendor/github.com/shaleman/libOpenflow/openflow13/match.go:89 +0x12f
github.com/haoyixin/netplugin/vendor/github.com/shaleman/libOpenflow/openflow13.(*PacketIn).UnmarshalBinary(0xc4201dadc0, 0xc4203a3800, 0x8c, 0x800, 0xc41ffbc204, 0xc420536690)
	/root/go/src/github.com/haoyixin/netplugin/vendor/github.com/shaleman/libOpenflow/openflow13/openflow13.go:351 +0x25d
github.com/haoyixin/netplugin/vendor/github.com/shaleman/libOpenflow/openflow13.Parse(0xc4203a3800, 0x8c, 0x800, 0xc42000c690, 0x193dd19, 0x8, 0xc420536770)
	/root/go/src/github.com/haoyixin/netplugin/vendor/github.com/shaleman/libOpenflow/openflow13/openflow13.go:135 +0x4be
github.com/haoyixin/netplugin/vendor/github.com/contiv/ofnet/ofctrl.(*Controller).Parse(0xc420449980, 0xc4203a3800, 0x8c, 0x800, 0x1, 0x4, 0x4, 0x166a480)
	/root/go/src/github.com/haoyixin/netplugin/vendor/github.com/contiv/ofnet/ofctrl/ofctrl.go:184 +0x54
github.com/haoyixin/netplugin/vendor/github.com/shaleman/libOpenflow/util.(*MessageStream).parse(0xc42010e500)
	/root/go/src/github.com/haoyixin/netplugin/vendor/github.com/shaleman/libOpenflow/util/stream.go:149 +0x19f
created by github.com/haoyixin/netplugin/vendor/github.com/shaleman/libOpenflow/util.NewMessageStream
	/root/go/src/github.com/haoyixin/netplugin/vendor/github.com/shaleman/libOpenflow/util/stream.go:68 +0x20d
```

**Comment by rchirakk** [comment]
Can you give some more details about your setup & what are you trying to do ?
if you are using kubernetes,
You don't need to add contiv service.

**Comment by haoyixin** [comment]
@rchirakk thx for reply

a relative issue you've answer before is https://github.com/contiv/netplugin/issues/885

then i did some, and that worked, but a new problem here

**Comment by rhim** [comment]
@haoyixin Are you building from source yourself? It would be nice for you to describe the following along with the issue:

Cluster hw - servers/networking gear
OS
Container platform/scheduler
Build version (if using our release), commit ID/branch otherwise

From the logs, it is evident that libOpenflow is not handling a specific packet type. 

`
2017/06/06 10:47:32 Unhandled Field: 105 in Class: 1
`

We need to dig in to find which packet is that. If you have more insight on it, please share.

**Comment by haoyixin** [comment]
@rhim thx for reply

HW: VMs on a private zstack
OS: CentOS Linux release 7.3.1611 (Core)
Platform: Mesos(unified containerizer)/Marathon
Build version: https://github.com/haoyixin/netplugin/commit/9e76c8463f9d987e51de54abb90abc535763648a

more detail on https://github.com/contiv/netplugin/issues/885

**Comment by ArikaChen** [comment]
I meet the same problem when using ovs 2.7.0:

1 create a pod
2 run `nslookup kubernetes` in pod
